### ISSUE TITLE
why minimal deployment target was set to iOS 13?

### ISSUE THREAD

**Issue by kukat** [imWildCat/ReactNativeAppleBinaryFramework#1]
https://github.com/imWildCat/ReactNativeAppleBinaryFramework/blob/35e1131c5e683d0e1907798eb184325da147b8bf/ReactNative-Binary.podspec#L15

I think the React Native 0.68.2 was compatible with iOS 11
https://github.com/facebook/react-native/blob/v0.68.2/React.podspec#L39

**Comment by imWildCat** [comment]
It was set for quick iteration. If you'd like to, we can have a PR to change it to `11.0`.

**Comment by imWildCat** [comment]
@kukat thanks for your PR. I've released <https://github.com/imWildCat/ReactNativeAppleBinaryFramework/releases/tag/v0.68.2.1>

Could you try?

**Comment by imWildCat** [comment]
We forgot to make this change: <https://github.com/imWildCat/ReactNativeAppleBinaryFramework/commit/ceffc6d448345f91b2d25c9c46977600803c6a6c>

If iOS 11 does not work as expected, we need to cherry-pick this commit.

**Comment by imWildCat** [comment]
Please note that iOS 12.4+ is required: https://github.com/facebook/react-native/commit/982ca30de079d7e80bd0b50365d58b9048fb628f
