### ISSUE TITLE
Dev functionality seems disabled

### ISSUE THREAD

**Issue by EvanBacon** [imWildCat/ReactNativeAppleBinaryFramework#6]
Hey, cool project.

DevMenu, hot reloading, websocket commands, etc. don't appear to be working. Curious if this needs to be precompiled with `RCT_DEV_MENU`, `RCT_DEBUG`, `RCT_DEV`, `RCT_ENABLE_INSPECTOR` enabled?

**Comment by imWildCat** [comment]
Hello Evan!

This is a good question. I'm investigating this problem. If you have any suggestions, please let me know!

**Comment by imWildCat** [comment]
Working on this:

1. `main` and PR ci: #8
2. TODO: release two sets of XCFrameworks

Looks like [CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/2847) and Swift Package don't support separating Debug and Release vendor frameworks.
So, I plan to publish two different CocoaPods for this binary.

**Comment by imWildCat** [comment]
(2) is going to be resolved in this build <https://github.com/imWildCat/ReactNativeAppleBinaryFramework/actions/runs/2605074349>

Going to refine the README.md tomorrow.

**Comment by imWildCat** [comment]
Resolved in #11 #12
